### ISSUE TITLE
Are there any plans for runtime configuration changes?

### ISSUE THREAD

**Issue by dkimot** [pipehub/pipehub#75]

**Comment by diegobernardes** [comment]
Not for now, maybe in the future. The thing is, PipeHub operates very different from other systems like Envoy. The configuration with PipeHub tends and are targeted to stay as minimal as possible. Also they're still the case of configurations that can't be changed at runtime.

But this doesn't block the pipe from doing runtime configuration. Take a look at this configuration:

```hcl
http "api.company.com" {
  handler = "base.Default"
}

pipe "github.com/company/pipe" {
  version = "v0.9.0"
  alias   = "base"

  config {
    redis {
      addr = "localhost"
      port = 6379
    }
  }
}
```

The pipe could connect into a redis and subscribe into a configuration key. PipeHub was built to do exactly this kind of stuff.

Besides that, do you still think that some other kind of runtime configuration should exist? Maybe is something that I'm not seeing.

**Comment by dkimot** [comment]
The use case I had in mind is similar to what Netflix uses their API gateway Zuul for. They have a great article you've probably seen, [here](https://medium.com/netflix-techblog/announcing-zuul-edge-service-in-the-cloud-ab3af5be08ee). In it, they mention using dynamic filtering to redirect specific users or groups of users to debug clusters, or A/B test clusters.

I may be projecting features onto PipHub that PipeHub wasn't designed to support, so please bear with my.

**Comment by diegobernardes** [comment]
> The use case I had in mind is similar to what Netflix uses their API gateway Zuul for. They have a great article you've probably seen, [here](https://medium.com/netflix-techblog/announcing-zuul-edge-service-in-the-cloud-ab3af5be08ee). In it, they mention using dynamic filtering to redirect specific users or groups of users to debug clusters, or A/B test clusters.
> 
> I may be projecting features onto PipHub that PipeHub wasn't designed to support, so please bear with my.

Not at all. This is exactly the case PipeHub was designed for. Take a look at this section of the documentation: https://pipehub.io/docs/overview#execution-flow, it shows the request lifecycle.

If you want to implement something like you're saying, the code should be something similar to this:
```golang
func (c Client) Default(next http.Handler) http.Handler {
	fn := func(w http.ResponseWriter, r *http.Request) {
		c.selectOriginTestAB(r)
		next.ServeHTTP(w, r)
	}
	return http.HandlerFunc(fn)
}

func (Client) selectOriginTestAB(r *http.Request) {
	switch r.URL.Query().Get("ab") {
	case "new":
		r.Host = "api-v2.company.com"
	case "old":
		r.Host = "api-v1.company.com"
	}
}
```

Note that on this example the host is hardcoded, but it could be injected at the configuration file or because it's a plain Go code, you could fetch it from other places, like a database.

You're really free to do anything: traffic shadowing, rate limit, change request, deny the request, etc...

If you need some help to test something, let me know. I can help you with the code or initial steps at the project.

**Comment by dkimot** [comment]
I see, that's awesome! I've only been working in Go a couple months now, but I'll definitely see if there are any issues I can help with. This looks like an exciting project!

**Comment by diegobernardes** [comment]
Thanks 😄
